<?php

namespace Presis\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HabilitacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HabilitacionesRepository extends EntityRepository
{
    public function findHabilitados(){
        die("avise al programador");
        $em=$this->getEntityManager();
        $dql='SELECT s.codServ,s.descripcion
                from PresisServicioBundle:Habilitaciones h
                join h.servicio s
                join h.cordonEntrega ce
                join h.cordonRetiro cr
                where ce.cpDesde<=:cpe
                and ce.cpHasta>=:cpe
                and h.horaDesde<=:hora
                and h.horaHasta>=:hora
                and cr.cpDesde<=(select suc3.cp from PresisGeneralBundle:Sucursal suc3 where suc3.id=1 and suc3.cliente=1)
                and cr.cpHasta>=(select suc4.cp from PresisGeneralBundle:Sucursal suc4 where suc4.id=1 and suc4.cliente=1)';
        $consulta=$em->createQuery($dql);
        $consulta->setParameter("cpe",1200);
        $consulta->setParameter("hora",new \DateTime('now'));

        return $consulta->getResult();


    }
}
