<?php

namespace Presis\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaRepository extends EntityRepository
{
    public function findTableData($user){
        $em=$this->getEntityManager();
        $dql='SELECT c
                from PresisGeneralBundle:Cliente c';

        $consulta = $em->createQueryBuilder()
            ->from('PresisServicioBundle:Lista', 'l')
            ->select("l.id,l.isGeneral,l.descripcion,c.empresa,v.nombre vendedor")
            ->leftJoin('l.vendedor', 'v')
            ->leftJoin('l.cliente', 'c');

        if ($user->hasRole("ROLE_VENDEDOR")){
            $consulta->where('l.vendedor = ?1')
                ->setParameter(1,$user->getVendedor());
        }
        $consulta=$consulta->getQuery();

        return $consulta->getResult();


    }
}
