<?php

namespace Presis\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListaFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaFileRepository extends EntityRepository
{
}
