<?php

namespace Presis\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioRepository extends EntityRepository
{
    public function findTableData($user){
        $em=$this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->from('PresisServicioBundle:Precio', 'p')
            ->select("p.id,p.rango,ce.descripcion cordonE,cr.descripcion cordonRetiro,l.descripcion lista,s.descripcion servicio,p.precio")
            ->leftJoin('p.cordonEntrega', 'ce')
            ->leftJoin('p.cordonRetiro', 'cr')
            ->leftJoin('p.servicio', 's')
            ->leftJoin('p.lista', 'l');

        if ($user->hasRole("ROLE_VENDEDOR")){
            $consulta->where('l.vendedor = ?1')
                ->setParameter(1,$user->getVendedor());
        }
        $consulta=$consulta->getQuery();

        return $consulta->getResult();


    }

    public function findByCliente($cliente, $servicio, $cordonRetiro, $cordonEntrega)
    {
        $em=$this->getEntityManager();

        $consulta = $em->createQueryBuilder()
            ->select('p')
            ->from('PresisServicioBundle:Precio', 'p')
            ->leftJoin('p.lista', 'l')
            ->where('l.cliente = :cliente')
            ->andWhere('p.servicio = :servicio')
            ->andWhere('p.cordonRetiro = :cordonRetiro')
            ->andWhere('p.cordonEntrega = :cordonEntrega')
            ->setParameter('cliente', $cliente)
            ->setParameter('servicio', $servicio)
            ->setParameter('cordonRetiro', $cordonRetiro)
            ->setParameter('cordonEntrega', $cordonEntrega)
            ->orderBy('p.rango', 'DESC');

        $consulta=$consulta->getQuery();

        return $consulta->getResult();
    }
}
