<?php

namespace Presis\ServicioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
    public function findHabilitadosApi($user,$cpe,$sucu_id){
        $collection = $user->getCliente()->getServicios();
        $serv_ids = $collection->map(function($entity)  {
            return $entity->getId();
        })->toArray();


        $consu2=$this->_em->createQueryBuilder();
        $consu2->select('identity(h.servicio)')
            ->from("PresisServicioBundle:Habilitaciones",'h')
            ->where('h.cordonEntrega=(Select ce from PresisServicioBundle:CpCordon ce where ce.cp=:ce)')
            ->andWhere('h.cordonRetiro=(Select cr from PresisServicioBundle:CpCordon cr where cr.cp=(Select suc.cp from PresisGeneralBundle:Sucursal suc where suc.codSuc=:sid))')
            ->andWhere('h.horaDesde <=:hora')
            ->andWhere('h.horaHasta >=:hora');








        $consulta=$this->createQueryBuilder('s');
        $consulta->where('s.id in (:serv)')
            ->andWhere($consulta->expr()->in('s.id',$consu2->getDQL()));

        $consulta->setParameter('serv',$serv_ids);
        $consulta->setParameter('ce',$cpe);
        $consulta->setParameter('sid',$sucu_id);
        $consulta->setParameter("hora",new \DateTime('now'));
        return $consulta->getQuery()->getResult();


    }
    public function findHabilitados($user,$cpe,$sucu_id){
       $collection = $user->getCliente()->getServicios();
        $serv_ids = $collection->map(function($entity)  {
            return $entity->getId();
        })->toArray();


        $consu2=$this->_em->createQueryBuilder();
            $consu2->select('identity(h.servicio)')
            ->from("PresisServicioBundle:Habilitaciones",'h')
            ->where('h.cordonEntrega=(Select identity(ce.cordon) from PresisServicioBundle:CpCordon ce where ce.cp=:ce)')
            ->andWhere('h.cordonRetiro=(Select identity(cr.cordon) from PresisServicioBundle:CpCordon cr where cr.cp=(Select suc.cp from PresisGeneralBundle:Sucursal suc where suc.id=:sid))')
            ->andWhere('h.horaDesde <=:hora')
            ->andWhere('h.horaHasta >=:hora');








        $consulta=$this->createQueryBuilder('s');
        $consulta->where('s.id in (:serv)')
                        ->andWhere($consulta->expr()->in('s.id',$consu2->getDQL()));

        $consulta->setParameter('serv',$serv_ids);
        $consulta->setParameter('ce',$cpe);
        $consulta->setParameter('sid',$sucu_id);
        $consulta->setParameter("hora",new \DateTime('now'));


        return $consulta;


    }
    public function findHabilitados2($user,$cpe,$sucu_id){
        $collection = $user->getCliente()->getServicios();
        $serv_ids = $collection->map(function($entity)  {
            return $entity->getId();
        })->toArray();

      //  ladybug_dump($sucu_id);
        $consu2=$this->_em->createQueryBuilder();
        $consu2->select('identity(h.servicio)')
            ->from("PresisServicioBundle:Habilitaciones",'h')
            ->where('h.cordonEntrega=(Select identity(ce.cordon) from PresisServicioBundle:CpCordon ce where ce.cp=:ce)')
            ->andWhere('h.cordonRetiro=(Select identity(cr.cordon) from PresisServicioBundle:CpCordon cr where cr.cp=(Select suc.cp from PresisGeneralBundle:Sucursal suc where suc.codSuc=:sid))')
            ->andWhere('h.horaDesde <=:hora')
            ->andWhere('h.horaHasta >=:hora');







        $consulta=$this->createQueryBuilder('s');
        $consulta->where('s.id in (:serv)')
            ->andWhere($consulta->expr()->in('s.id',$consu2->getDQL()));

        $consulta->setParameter('serv',$serv_ids);
        $consulta->setParameter('ce',$cpe);
        $consulta->setParameter('sid',$sucu_id);
        $consulta->setParameter("hora",new \DateTime('now'));

        $res=$consulta->getQuery()->getResult();
      //  ladybug_dump($res);
        return $consulta->getQuery()->getResult();


    }
}
