parameters:
#    presis_api.example.class: Presis\ApiBundle\Example

services:
#    presis_api.example:
#        class: %presis_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
