comprador:
    path:     /
    defaults: { _controller: "PresisRetiroBundle:Comprador:index" }

comprador_show:
    path:     /{id}/show
    defaults: { _controller: "PresisRetiroBundle:Comprador:show" }

comprador_new:
    path:     /new
    defaults: { _controller: "PresisRetiroBundle:Comprador:new" }

comprador_create:
    path:     /create
    defaults: { _controller: "PresisRetiroBundle:Comprador:create" }
    requirements: { _method: post }

comprador_edit:
    path:     /{id}/edit
    defaults: { _controller: "PresisRetiroBundle:Comprador:edit" }

comprador_update:
    path:     /{id}/update
    defaults: { _controller: "PresisRetiroBundle:Comprador:update" }
    requirements: { _method: post|put }

comprador_delete:
    path:     /{id}/delete
    defaults: { _controller: "PresisRetiroBundle:Comprador:delete" }
    requirements: { _method: post|delete }
