<?php

namespace Presis\DistribuidorBundle\Entity;

/**
 * PresentismoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentismoRepository extends \Doctrine\ORM\EntityRepository
{
}
