tiporeclamo:
    path:     /
    defaults: { _controller: "ReclamoBundle:TipoReclamo:index" }

tiporeclamo_show:
    path:     /{id}/show
    defaults: { _controller: "ReclamoBundle:TipoReclamo:show" }

tiporeclamo_new:
    path:     /new
    defaults: { _controller: "ReclamoBundle:TipoReclamo:new" }

tiporeclamo_create:
    path:     /create
    defaults: { _controller: "ReclamoBundle:TipoReclamo:create" }
    methods:  POST

tiporeclamo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReclamoBundle:TipoReclamo:edit" }

tiporeclamo_update:
    path:     /{id}/update
    defaults: { _controller: "ReclamoBundle:TipoReclamo:update" }
    methods:  [POST, PUT]

tiporeclamo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReclamoBundle:TipoReclamo:delete" }
    methods:  [POST, DELETE]
