<?php

namespace Presis\RemitentesBundle\Entity;

/**
 * RemitenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRemiByCliente($codcli){

        $consulta=$this->createQueryBuilder('r');
        $consulta->where('r.cliente = :codcli');
            $consulta->setParameter('codcli',$codcli);
        return $consulta;


    }
}
