<?php

namespace Presis\CecosBundle\Entity;

/**
 * CecosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CecosRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCecoByCliente($codcli){
        $consulta=$this->createQueryBuilder('c');
        $consulta->where('c.cliente = :codcli');
        $consulta->setParameter('codcli',$codcli);
        return $consulta;
    }

}
