# Presis/GestionCelBundle/Resources/config/validation.yml
Presis\GestionCelBundle\Entity\GestionCel:
    properties:
        usuario:
            - NotBlank: ~
        ani:
            - NotBlank: ~
            - Length:
                min: 10
                max: 10
                minMessage: "el campo ani debe contener minimo {{ limit }} numero"
                maxMessage: "el campo ani debe contener maximo {{ limit }} numeros"
            - Regex: "/^[0-9]+$/"

        nroserie:
            - NotBlank: ~
            - Length:
                min: 15
                max: 15
                minMessage: "el campo numero de serie debe contener minimo {{ limit }} numero"
                maxMessage: "el campo numero de serie debe contener maximo {{ limit }} numeros"
            - Regex: "/^[0-9]+$/"

        nomyape:
            - NotBlank: ~
            - Length:
                min: 1
                max: 30
                minMessage: "el campo nombreapellido debe contener minimo {{ limit }} numero"
                maxMessage: "el campo nombreapellido debe contener maximo {{ limit }} numeros"

        nrosst:
            - NotBlank: ~
            - Length:
                min: 13
                max: 13
                minMessage: "el campo nrosst debe contener minimo {{ limit }} numero"
                maxMessage: "el campo nrosst debe contener maximo {{ limit }} numeros"
            - Regex: "/^[0-9]+$/"


