<?php

namespace Presis\RetiroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompradorRepository extends EntityRepository
{
}
