<?php

namespace Presis\RetiroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SenderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SenderRepository extends EntityRepository
{
}
