<?php

namespace Presis\ConstanciaRetiroBundle\Entity;

/**
 * ConstanciaRetiroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstanciaRetiroRepository extends \Doctrine\ORM\EntityRepository
{

}
