<?php

namespace Presis\ConstanciaRetiroBundle\Entity;

/**
 * RetirosFijosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetirosFijosRepository extends \Doctrine\ORM\EntityRepository
{
}
