parameters:
#    presis_fixture.example.class: Presis\FixtureBundle\Example

services:
#    presis_fixture.example:
#        class: %presis_fixture.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
