<?php

namespace Presis\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function findTableData($user){
        $em=$this->getEntityManager();
        /*$dql='SELECT c
                from PresisGeneralBundle:Cliente c';*/
        //die($user->getVendedor());
        $consulta = $em->createQueryBuilder()
            ->from('PresisGeneralBundle:Cliente', 'c')
            ->select("c.id,c.empresa,c.contacto,c.aforo,l.descripcion lista,r.descripcion rubro,v.nombre vendedor,c.custom_price_list lp")
            ->leftJoin('c.rubro', 'r')
            ->leftJoin('c.lista', 'l')
            ->leftJoin('c.vendedor', 'v');
            if ($user->hasRole("ROLE_VENDEDOR")){
                $consulta->where('c.vendedor = ?1')
                        ->setParameter(1,$user->getVendedor());
            }
         $consulta=$consulta->getQuery();

        return $consulta->getResult();


    }
}
