<?php

namespace Presis\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImpoTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImpoTestRepository extends EntityRepository
{
}
