<?php

namespace Presis\GeneralBundle\Entity;

/**
 * ManifiestoCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManifiestoCargaRepository extends \Doctrine\ORM\EntityRepository
{
}
