<?php

namespace Presis\GuiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuiaRepository extends EntityRepository
{
}
