<?php

namespace Presis\TipoDNIBundle\Entity;

/**
 * TipoDniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDniRepository extends \Doctrine\ORM\EntityRepository
{
}
