<?php

namespace Presis\FirmasBundle\Entity;

/**
 * FirmasManifiestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmasManifiestoRepository extends \Doctrine\ORM\EntityRepository
{
}
