<?php

namespace Presis\FirmasBundle\Entity;

/**
 * FirmasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmasRepository extends \Doctrine\ORM\EntityRepository
{
}
