<?php

namespace Presis\MovistarBundle\Entity;

/**
 * CompletitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompletitudRepository extends \Doctrine\ORM\EntityRepository
{
}
