<?php

namespace Presis\MovistarBundle\Entity;

/**
 * FallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FallaRepository extends \Doctrine\ORM\EntityRepository
{
}
