<?php

namespace Presis\MovistarBundle\Entity;

/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends \Doctrine\ORM\EntityRepository
{

    public function findModeloByFabricante($codfabri){
    	$true = '1';
        $consulta=$this->createQueryBuilder('c');
        $consulta->join('MovistarBundle:Fabricante', 'f');
        $consulta->where('c.fabricante = :fabricante');
        $consulta->andWhere('c.activo = :activo');
        $consulta->setParameter('fabricante',$codfabri);
        $consulta->setParameter('activo',$true);
        return $consulta;
    }

}
