<?php

namespace Presis\MovistarBundle\Entity;

/**
 * ServiciosMovistarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosMovistarRepository extends \Doctrine\ORM\EntityRepository
{
}
